#include <cmath>
#include <cstdlib>
#include <ctime>
#include <iostream>
#include <string>
#include <iomanip>

using namespace std;

// P = p x Q x H x g
// p = 1000
// g = 9.81


// Prototype Functions
double powerGen (double Q, double H);

// Main Function
int main ()
{
double Q;
double H;

cout << "Calculates the power generated by a turbine in watts." << endl;
cout << endl;

cout << "Enter Q (Waterflow):" << endl;
cin >> Q;
cout << endl;
cout << "Q = " << Q << " m^3/s" << endl;
cout << endl;

cout << "Enter H (Height of Fall):" << endl;
cin >> H;
cout << "H = " << H << " Meters high" << endl;

cout << setprecision(7) << endl;
powerGen(Q, H);
}

//Function for power generation - Watts:
double powerGen (double Q, double H)
{
double g = 9.81;
double p = 1000;

double Power;

cout << endl;
cout << "The resulting power is: " << (p * Q * H * g) << " watts";

return Power;
}