/*
Programmer: Zachary Luevano
Date Finished 29 September 2022

Description: Calculates the power in wattage that is ouputted given a set of variables that are inputed into a prototype function powerGen, using a couple of set numbers of q and P the program essentially just takes two inputs enters them in an equation does the math and outputs the results back out.
*/
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <iostream>
#include <string>
#include <iomanip>

using namespace std;

// P = p x Q x H x g
// p = 1000
// g = 9.81


// Prototype Functions
double powerGen (double Q, double H);

// Main Function
int main ()
{
double Q;
double H;

cout << "Calculates the power generated by a turbine in watts." << endl;
cout << endl;

cout << "Enter Q (Waterflow):" << endl;
cin >> Q;
cout << endl;
cout << "Q = " << Q << " m^3/s" << endl;
cout << endl;

cout << "Enter H (Height of Fall):" << endl;
cin >> H;
cout << "H = " << H << " Meters high" << endl;

cout << setprecision(7) << endl;
powerGen(Q, H);
}

//Function for power generation - Watts:
double powerGen (double Q, double H)
{
double g = 9.81;
double p = 1000;

double Power;

cout << endl;
cout << "The resulting power is: " << (p * Q * H * g) << " watts";

return Power;
}

// Case A as in book = 2746800 Watts
// Case B as in book = 5886000 Watts
// Both cases are just multiplying p * Q * H * g, cases were verified using a calculator the results do infact calculate correctly.